### ISSUE TITLE
Is raw data available?

### ISSUE THREAD

**Issue by TomHarte** [andete/ym2413#1]
I'm guessing you moved on a long time ago, possibly meaning that the various graphs here are all that remains of your original data but supposing any of the raw data survives it'd be really useful to have for unit testing purposes.

(and, yes, when you've already done so much, I feel terrible about enquiring about more)

**Comment by andete** [comment]
I guess this is mostly a question for @m9710797 who has the testing device and did most of the testing.

**Comment by m9710797** [comment]
Hi TomHarte,

Some (most?) of the raw data is still available, but it's not well organized, so for many data I don't know anymore _exactly_ what was measured. And it's really _raw_ data. Translating from the raw data to the processed data you see in the graphs means:
- Cropping the data in time.
- Map the 16-bit captured data to 9-bit YM2413 samples (that is: group the 65536 possible raw value into 512 possible YM2413 values).

For best results this last step needs a "calibration file" because I found that, from day-to-day or morning/evening, measuring the same sound does not always result in the same 16-bit data. Possibly the ADC has some temperature dependence? I don't have those calibration files anymore. For some purposes that's not a big problem, it will only introduce slight classification error. And even with proper calibration there are occasional errors. But it does make this raw data ill suited for unit testing (where you need exact data).

If you have specific requests I can dig up the data. But I don't think it's very useful to just publish all unorganized raw data.

Ah, but maybe I misunderstood: maybe you mean with "raw data" the numerical (but "processed") data that's shown in the graphs?


I would like to point you to this project:
    https://github.com/nukeykt/Nuked-OPLL
This project claims to be a cycle accurate YM2413 emulator. And I can confirm that it matches with all the results of my own research (actually I did report 3 small problems and those have been fixed since).

The goal of this project was to improve the YM2413 emulation in openMSX. I've now integrated the NukeYKT core in openMSX, so I consider this project as mostly finished. The only thing I still like to do (but low priority) is some kind of integration-test or stress-test: capture a whole song on the YM2413 test board and compare that with the NukeYKT output. 

Wouter

**Comment by TomHarte** [comment]
So as not to imply I was being more intelligent than I was: I was just thinking of the numbers that were used to produce each graph, so the set you arrived at as ideal; at present I'm testing my implementation by plotting a graph and comparing by sight, which is a thousandfold better than just listening, and makes me extremely grateful for the work you've done, but is still a slightly obtuse way of proceeding.

Completely raw data might also fill in some other gaps, e.g. exactly how the time multiplexing works. How long on each channel, when rhythm output is voiced, etc, but that's not really what I was getting at.

Anyway, if the project's done then that's probably the end of that. You've already massively improved the amount of information available so that's fantastic. I unfortunately can't really look at Nuked-OPLL because my emulator uses a more permissive licence than GPL2 and therefore I daren't risk absorbing any of his implementation details. But I did find the instrument list at https://siliconpr0n.org/archive/doku.php?id=vendor:yamaha:opl2#ym2413_instrument_rom so between that and your work I think I have many of the details.

Please feel free to mark this issue as closed given that this project is considered mostly finished.

**Comment by m9710797** [comment]
Aha, you're making another YM2413 emulator? Very interesting. Can you tell me more about it?

I'm also glad to hear that my work was useful for you. It's true that I consider my research as (mostly) finished. But if there's anything I can still do to help you, then feel free to ask.

I don't know what is and what is not allowed license-wise for your work. Is it OK to use the NukeYKT (GPL2) code to generate test-vectors and compare those with your implementation? Or maybe if you have specific questions about the algorithm, I could study the NukeYKT code and describe the algorithm to you?

You can ask questions here or you can contact me directly (vermaelen.wouter@gmail.com).

**Comment by TomHarte** [comment]
Re: my emulation; I'm the author of an ever-growing multiplatform emulator that includes the MSX 1 and Master System, but so far I've not implemented any sort of FM synthesis. So I thought the YM2413 would be a good first bridge to cross, especially now that the fixed instruments are fully specified, as I have two systems ready to use it immediately. Such is my trajectory that I'm sure I'll want to do other OPLs, and OPNs in the future so as well as the basic issue of code licensing I'm writing my own as an educational endeavour and because I expect to reuse parts later (for the OPLs, anyway) so that suggests a more verbose structure.

I'm not expecting it necessarily to be as good as other implementations but obviously the better my sources of information the fewer the obstacles to that.

So, I'm not even quite done on melodic channels yet, but they seem to be fully specified so there's nothing much to ask on that.

So unknowns are:
* primarily the time-division multiplexer, and how it schedules, and especially what it does in rhythm mode when the number of sound sources is no longer an even divider of 72 (actually additively mixes down the high-hat and snare for channel 7, and the cymbal and tom tom for channel 8, I'd guess, but...); and
* every rhythm instrument other than the high hat, which is documented [by carbon14 on http://forums.submarine.org.uk](http://forums.submarine.org.uk/phpBB/viewtopic.php?f=9&t=1174). I guess the other LFSR drums are similar, probably indexing different phase generator bits, but the non-LFSR bass drum in particular is not something I've yet seen information on.

**Comment by m9710797** [comment]
If I understood your two questions correctly, then I think they're answered in my last 'article':
  https://github.com/andete/ym2413/blob/master/results/rhythm/rhythm.md
If not then please ask again.

**Comment by TomHarte** [comment]
I hadn't seen that article, which is my own fault. I've been reading the mirrors at smspower.org, which are out of date. I apologise, and downgrade credence accordingly.

I think that conceptually I have only a few remaining conceptual failings:

- it's unclear to me from your document which operators the high-hat relies on. The `c85` and `m77`-style syntax for the cymbal is pretty clear, but for the high-hat you've switched to just `b85` and `b77`;
- actually, looking at the drums suggests I've also possibly misunderstood the envelope generators. I've got them one per operator, with key-on propagating to both operators from channels in regular melodic mode, but: (i) possibly ADSR isn't applied to modulators — it's only the raw phase output and the fixed attenuation that matter?; and (ii) if it is, then I don't see how you don't end up with at least two drums sharing at least one ADSR envelope given that they share operators, which would make their key on/off bits not quite independent.

Once again though, if I'm just pestering you then please disregard. What you've already provided has made this whole process a million times easier than I was imagining it would be.

EDIT: I think the above is potentially unclear, so to explain:

The bass drum, cymbal and high hat each use two operators. The snare and rom tom each use one operator. So the number of operator inputs to the rhythm section is 8. There are only six operators feeding those eight inputs. Since the cymbal and high-hat use the phase of their second operator directly, they definitely don't need to pay attention to that operator's ADSR. So — assuming modulators apply ADSR just like carriers — you do need only six ADSR units. So then I think I've basically circled back to just being unclear about which operators are powering the high-hat.

**Comment by m9710797** [comment]
Hi Thomas,

No need to apologize, I'm happy to help.

>     * it's unclear to me from your document which operators the high-hat relies on. The `c85` and `m77`-style syntax for the cymbal is pretty clear, but for the high-hat you've switched to just `b85` and `b77`;
Thanks for pointing this out, I've corrected it in my article (switched 'b85' -> 'c85', etc).

About the operator allocation:
* For the BD sound it's clear(?), it behaves exactly the same as the melodic channels.
* The other 4 sounds (SD, TOM, TCY, HH) use the resources of the last two melodic channels. A channel has 2 operators. So there are (only) 4 operators for these 4 sounds. An operator has two main parts: an envelope generator (EG, for the ADSR stuff) and a phase generator (PG). Each of these 4 rhythm sounds uses it's own (private) EG, but the PG is sometimes shared. More in detail:
** SD: uses private EG and PG (car7)
** TOM: uses private EG and PG (mod8)
** TCM: uses private EG (car8) and shared PG (car8 and mod7)
** HH: uses private EG (mod7) and shared PG (car8 and mod7)

ADSR _is_ applied to both the modulator and the carrier EG. As a first approximation you can indeed apply the key-on/off bit of the channel to both EG's (But each EG has its own settings for attack rate, decay rate, sustain level and release rate). Note that (for the last two channels) the key-on/off bit works slightly different in melodic than in rhythm mode: in melodic mode the two operators have a shared bit in the channel, in rhythm mode the operators have a private bit (in register 0xE).

[ I'm not 100% sure, I think this paragraph applies to the YM2413, but not to (some/all) of the other Yamaha FM-chips. ]
More in detail: next to the 4 ADSR states (Attack, Decay, Sustain, Release) there's a 5th state: "Damp". This state only exists for the carrier, not for the modulator. When the key-bit is switched off->on, the EG does not immediately switch to the Attack state. Instead the envelope first rapidly goes to maximum attenuation (as-if you had selected release-rate=12). When maximum attenuation is reached, the phase of both operators (carrier and modulator) is reset to zero and both go to the Attack state. (During the carrier Damp phase, the modulator continues normally: it's not yet "aware" of the key off->on change.)

Wouter

**Comment by TomHarte** [comment]
Thanks for the tip! I had previously avoided sudden jumps in phase by not resetting phase if heading into attack when release hadn't completed; I've now added damp for all carriers, including the bass drum's, and for the tom tom.

It's actually not sounding terrible now — I've put out an initial release of my emulator so maybe I'll get further feedback and maybe I won't. I know offhand that I have the precisions wrong in a couple of places and I'm sure I probably have at least one attenuation scale off, but it mostly sounds good, albeit very quiet because the time-division multiplexing is problematic in strict integer-range terms.

One thing that very manual testing made me curious about: does tremolo apply to a note that has fully released? I have seen at least one aside reference to channels having a genuine 'off' mode, not just sitting at maximum release attenuation, but I didn't manage to locate that clue again.

**Comment by m9710797** [comment]
Tremolo (called Amplitude Modulation (AM) in the YM2413 datasheet) is fully decoupled from the Envelope Generator (EG) state. Same for Vibrato (VIB). Actually there's only one AM/VIB state that is shared among all (2 x 9) operators. Or to more directly answer your question: even for an 'off'-mode channel, the AM/VIB stuff keeps running. 

Note that this shared global state makes it harder to 'unittest' YM2413 emulators, or at least to directly compare their output to captured real YM2413 output. If you play the exact same sound (all user settings the same) multiple times, but start it a little sooner or later, the status of the global AM/VIB stuff is likely different. And that will result in a different produced waveform (of course it does still sound the same). And similar for the exact timing of EG steps, those also depend on a shared global counter.

**Comment by TomHarte** [comment]
I meant more: if a note has been fully released then both its carrier and modulator will be sitting at attenuation 127.

If there were no 'off' mode and the channel's instrument applies amplitude modulation, the channel would periodically rise above attenuation 127. I'm sure it'd still be quiet enough that I couldn't hear it, but other people have better ears than I do and it feels like something you'd want to eliminate anyway as a potential source of noise.

So the question was more about whether there really is a per-channel on/off bit, presumably with the envelope generator announcing when 'off' can be applied, and key-on being used to switch back to 'on'.

I guess you already answered by confirming that channels do go completely off.

So I guess I'll say that there is only one other thing I found a bit confusing in your documentation, which was the implementation of the attack phase as:

    start with: x = 127;
    advance: x += ~x >> 2;

If x is a 7-bit quantity then ~x is 0. So you'd never advance from full attenuation. I figured out that I should either: (i) assume a signed type for x greater than 7 bits, and an implementation in which shifts are signed; or (ii) imagine that >> has higher precedence than ~; but phrasing it as `x += ~(x >> 2)` might be a bit clearer?

Anyway, I think I've dragged us well into the weeds so I'm going to mark this as closed.

Thanks again!

**Comment by m9710797** [comment]
Hi,

About the 'off state', I believe that the real YM2413 hardware doesn't have a real off state. All calculations are performed as-if the release state lasts forever. However when the EG-level of the carrier-operator is >= 124 then the output of that channel is muted. So it looks like there is this 'off-state' (but in subtle edge-cases this implementation difference becomes visible).

About the formula "x += ~x >> 2", the next line in the article gives the sequence that is generated by this formula: 127, 95, 71, 53, 39, 29, 21, 15, 11, 8, 5, 3, 2, 1, 0. The formula must be evaluated as if it is C code with the usual integer promotion rules. Short summary: the sub-expression '~x' produces a wider than 7-bit result (with upper bits equal to 1) and then the shift operation shifts those 1-bits into the lower 7 bits positions.

Note that this is only an approximate formula which I made up near the start of my research. I later described a more accurate formula in:
   https://github.com/andete/ym2413/blob/master/results/20170126/attack.txt

Wouter

**Comment by TomHarte** [comment]
Yeah, it only by following the examples that I understood what was
being communicated, so I thought I'd pass it along as a reader's comment.

Trying to come up with an intellectual reason as to why I had to work
through the examples, which is probably a little artificial but there it
is, I think it was because you have to assume both two's complement and
arithmetic shifts, and neither is a guarantee in C. Though two's complement
is a guarantee in C++20. Every modern compiler provides both, but  as an
emulator author particularly I spend my days with more obscure
architectures.

So definitely leave it if you think it's clear, but at least to this reader
the non-portable C reading wasn't what I jumped straight to.

**Comment by grauw** [comment]
Hey Tom, if you want a stress test, test with my [FM PCM player](http://www.grauw.nl/projects/fmpcm/). It relies on an accurate operator phase implementation (+ phase reset test register flag).

I’ve also posted a bunch of additional tests [here](https://github.com/openMSX/openMSX/issues/581), including recordings from real hardware.
